Parameters:
  stack:
    Type: String
    Description: Stack
  app:
    Type: String
    Description: App
  stage:
    Type: String
    Description: Stage
  capi:
    Type: String
    Description: Capi key
Resources:
  EditionsBackendServiceRole74FAA4BE:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                Fn::Join:
                  - ""
                  - - lambda.
                    - Ref: AWS::URLSuffix
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: EditionsStack/EditionsBackend/ServiceRole/Resource
  EditionsBackendServiceRoleDefaultPolicy6C36170A:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - :s3:::editions-dist
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - :s3:::editions-dist/*
        Version: "2012-10-17"
      PolicyName: EditionsBackendServiceRoleDefaultPolicy6C36170A
      Roles:
        - Ref: EditionsBackendServiceRole74FAA4BE
    Metadata:
      aws:cdk:path: EditionsStack/EditionsBackend/ServiceRole/DefaultPolicy/Resource
  EditionsBackend45ED90CB:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: editions-dist
        S3Key:
          Fn::Join:
            - ""
            - - Ref: stack
              - /
              - Ref: stage
              - /backend/backend.zip
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - EditionsBackendServiceRole74FAA4BE
          - Arn
      Runtime: nodejs8.10
      Environment:
        Variables:
          CAPI_KEY:
            Ref: capi
      FunctionName:
        Fn::Join:
          - ""
          - - editions-backend-
            - Ref: stage
    DependsOn:
      - EditionsBackendServiceRoleDefaultPolicy6C36170A
      - EditionsBackendServiceRole74FAA4BE
    Metadata:
      aws:cdk:path: EditionsStack/EditionsBackend/Resource

